* Data generation

** QFeatures data produced in R

The data is from

     Ai, Lizhuo, Aleksandra Binek, Vladimir Zhemkov, Jae Hyung Cho, Ali
     Haghani, Simion Kreimer, Edo Israely, et al. 2025. “Single Cell
     Proteomics Reveals Specific Cellular Subtypes in Cardiomyocytes
     Derived from Human iPSCs and Adult Hearts.” Mol. Cell. Proteomics,
     no. 100910 (January): 100910.
     https://doi.org/10.1016/j.mcpro.2025.100910.

See the [[https://rformassspectrometry.github.io/MsDataHub/reference/Ai2025.html][data manual page]] for additional details and [[https://lgatto.github.io/2025-EuBIC-SCP-hackathon/][2025 EuBIC SCP
hackathon vignette]].

- =make-data_ai2025acms.R=: loads the DIANN output from
  =data/Ai2025_aCMs_report.tsv= (available [here]()) to create a
  =QFeatures= object.
- The resulting =QFeatures= object is serialised to
  [=data/ai2025a.rda=](data/ai2025a.rda).
- The individual sets are also exported to csv files stored as
  =data/[221024_Subject|precursors|peptides|proteins]...csv=,  and the main cell/sample metadata is
  exported as [=data/ai2025a-colData.csv=](ai2025a-colData.csv).

The required environment, script and data are also available as [[https://hub.docker.com/repository/docker/lgatto/ai2025a/general][a
docker container]]:

#+begin_src shell
docker run -it --user rstudio lgatto/ai2025a R
#+end_src

See the [[https://bioconductor.org/help/docker/][Docker for Bioconductor]] page for more help.

** mulink data produced in python.

The data was generated as documented in [[https://github.com/lucas-diedrich/ms-scverse-bioconductor/][ms-scverse-bioconductor]].

* R/Python on-disk representation

The different `make-data_.R` scripts import data from `scpdata`,
serialise it in `h5mu` with `writeLinkH5MU()` from
[[https://github.com/lucas-diedrich/ms-scverse-bioconductor][ms-scverse-bioconductor]], and then reload it with `readLinkH5MU()`. The
observed differences are collected in the scripts and associated
issues.

To consolidate this round-trip, initiated by Lucas Diedrich
[[https://github.com/lucas-diedrich/ms-scverse-bioconductor][ms-scverse-bioconductor]], we are porting/rewriting some of that code in
the [[https://github.com/UCLouvain-CBIO/mulinkr][mulinkr]] package.

* License

All the code in this repository is provided under GPL-3.0 license.